### ISSUE TITLE
feat: design minimalistic error pages (404)

### ISSUE THREAD

**Issue by ssddOnTop** [ssddOnTop/spacepls#1]
In order to throw proper error response, we need to design proper HTML error pages.

### Scope
Scope of this issue is just to make 2 minimalist html pages with minimal design and code.

### Pages
The pages should display following response code.

1. 404
2. ~~500~~

**Edit:**

Reducing scope of the issue to just 404 page.

The HTML file should be placed in new html folder in the root dir.
```
html
  - 404.html
```
  
The html should have a script that automatically displays available routes based on given JSON string.

Example:

```json
{
"available_routes": ["foo", "bar"]
"foo": "Some description for foo",
"bar": "Some description for bar"
}
```

From the JSON mentioned above, it should display available route and its description.  

The JSON won't be hardcoded in JS, there should be some unique string which can be replaced by JSON string like:

```js
let routesJSON = 'SOME_UNIQUE_STRING_TO_BE_REPLACED'
```

so at the compile time this string will be replaced with available routes and their description.

**Comment by htomar6397** [comment]
@ssddOnTop 
I had designed, what next to do?

**Comment by ssddOnTop** [comment]
@htomar6397 I edited the issue.. have a look and make a PR

**Comment by htomar6397** [comment]
/attempt #1

<div id="algora" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cltcftyd50002ia0ffwdy9y6v/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>
